app:
  appName: 百度
  appVersion: 1.0.0
  versionCode: 1
  applicationId: com.hezhihu89.yamlconfig
injectParams:
  aliyunApiKey: jr94i93ir943r9i4jfjkkwo203
  wxApikey: ji009jj9ir4jf4jfj949f4if
  apiCode: 1000
module:
  androidx.core:core-ktx: 1.3.2
  androidx.appcompat:appcompat: 1.6.0
  com.hezhihu89.modules:module1: 2.0.0
  com.hezhihu89.modules:module2: 1.0.0-SNAPSHOT
library:
  com.hezhihu89.base:
    version: 1.0.0
    include: true
    modules:
      base:
        path: base1
  com.hezhihu89.modules:
    path: modules
    version: 2.0.0
    include: true
    modules:

      module1:
        path: module1

      module2:
        version: 3.0.0
        include: false
        path: module2
