app:
  appName: 百度
  appVersion: 1.0.0
  versionCode: 1
  applicationId: com.hezhihu89.yamlconfig
mavenPublishGradleFile: "mavenUpload.gradle"
module:
  androidx.core:core-ktx: 1.3.2
  androidx.appcompat:appcompat: 1.6.0
  com.hezhihu89.modules:module1: 1.0.0
  com.hezhihu89.modules:module2: 1.0.0
library:
  com.hezhihu89.modules:
    path: modules
    version: 1.0.0
    include: true
    modules:
      module1:
        path: module1
      module2:
        path: module2
