/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.hezhihu89.config

import com.android.build.gradle.AppExtension
import com.android.build.gradle.internal.dsl.BaseAppModuleExtension
import com.hezhihu89.maven.ProjectMavenConfig
import com.hezhihu89.module.App
import com.hezhihu89.transform.ParamsInjectTransform
import com.hezhihu89.utils.YamlUtils
import org.gradle.api.*

fun Project.`android`(configure: Action<BaseAppModuleExtension>): Unit =
    (this as org.gradle.api.plugins.ExtensionAware).extensions.configure("android", configure)

/**
 * A simple 'hello world' plugin.
 */
class YamlConfigPlugin: Plugin<Project> {

    override fun apply(project: Project) {
        // Register a task
        val appConfig: App = YamlUtils.getAppConfig(project)
        project.addAppConfigExtensions("app",appConfig)
        project.addAppConfigExtensions("appConfig",appConfig.app)

        project.subprojects.forEach { subProject ->
            subProject.addAppConfigExtensions("appConfig",appConfig.app)
            ReplaceModule2Library.create(subProject).apply(appConfig)
            ProjectMavenConfig.create(subProject).apply()
            if(subProject.name == "app"){
                subProject.afterEvaluate {
                    val app = subProject.extensions.getByType(AppExtension::class.java)
                    app.registerTransform(ParamsInjectTransform("2",subProject,appConfig))
                }
            }
        }
    }

    private fun Project.addAppConfigExtensions(name: String,appConfig: Any){
        extensions.add(appConfig.javaClass, name, appConfig)
    }

}