/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.hezhihu89

import org.gradle.internal.impldep.org.apache.maven.settings.building.SettingsBuilder
import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.hezhihu89.greeting' plugin.
 */
class YamlconfigPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.hezhihu89.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
